### ISSUE TITLE
Menu items when log in by executive user

### ISSUE THREAD

**Issue by RohanBee** [FTXInfotech/laravel-adminpanel#460]
I need to display the custom module's menu items when loggin in with executive user. I have already set up the roles and updated the executive user with permission to handle all the required actions of my models but they are not being displayed in the menu items. The access management, faq, blog, and settings (pre-defined ones) are being displayed tho.

**Comment by alanwhitmore** [comment]
We have resolved this in the new version. Please try the new version.
