### ISSUE TITLE
IE11 Doesn't display some controls

### ISSUE THREAD

**Issue by jbernier** [FTXInfotech/laravel-adminpanel#531]
Hi,

Installed the demo. When using IE11 to test it there is few controls that doesn't show (checkbox,radio, etc).

Is this admin compatible with IE11 ? Edge and Chrome working fine.

**Comment by krguptaa** [comment]
Hi @jbernier ,

Thanks for letting us know. We will looking into this in new release.

**Comment by alanwhitmore** [comment]
We have resolved this in the new version. Please try the new version.
