### ISSUE TITLE
TinyMCE image upload not found 

### ISSUE THREAD

**Issue by NayHtwe24** [FTXInfotech/laravel-adminpanel#588]

**Comment by NayHtwe24** [comment]
![screenshot-localhost_8000-2020 01](https://user-images.githubusercontent.com/43719216/72882927-d1c10080-3d31-11ea-9fd6-904bc215e642.png)

**Comment by NayHtwe24** [comment]
How to fix it

**Comment by Jerinvjose** [comment]
Any update on this?

**Comment by Jerin-deepnet** [comment]
This is due to the tinymce version. For a temporary workaround, you can change the tinymce version to 4.9.8 and comment the "theme: 'silver'" line from backend-custom.js file. The reason for this issue is in tinymce version 5, the file_browser_callback is removed.

**Comment by baduypaltalk** [comment]
![image](https://user-images.githubusercontent.com/8188362/82276999-00ce4280-99b1-11ea-87e8-3083e331cbf8.png)

Hi there,
In this project  sources, but "upload tab" or Upload browser still does not appear ! Plz help me @viralsolani  @bvipul

**Comment by baduypaltalk** [comment]
Nobody here :) 
But i've already resolved this issue. 
it's so comfortable. 👯 

Thanks for read.

**Comment by in-sohelrana** [comment]
> t's so comforta

please describe it how to solve

**Comment by in-sohelrana** [comment]
@baduypaltalk 
please describe it how to solve

**Comment by baduypaltalk** [comment]
u can add my skype  "quocduy.itvn"
Regards,

**Comment by alanwhitmore** [comment]
We have resolved this in the new version. Please try the new version.
