### ISSUE TITLE
Use of abandoned packaged

### ISSUE THREAD

**Issue by rabol** [FTXInfotech/laravel-adminpanel#597]
when installing or updating (composer update) one get this warning:

Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

**Comment by alanwhitmore** [comment]
We have fixed issues in the new release. please check and let me know if you still find it.
