### ISSUE TITLE
Permission not working 

### ISSUE THREAD

**Issue by rhaider-dev** [FTXInfotech/laravel-adminpanel#603]
If you edit executive permission and remove faq view and update it still shows the faq mangement section for executive.

You can see the bug in your demo also. I have the same issue for myself in localhost. Please fix the issue ASAP.

**Comment by NModern** [comment]
Hi. You can fix it with changing in routes/backend/auth.php line 87 "PermissionController" to "PermissionsController"

**Comment by rhaider-dev** [comment]
Thanks for your reply. I will do that.
