### ISSUE TITLE
Error when create module

### ISSUE THREAD

**Issue by tranhueminh89** [FTXInfotech/laravel-adminpanel#604]
I have installed Laravel 6.0 AdminPanel but when I can't create module. Pls help me check this error.
<img width="1054" alt="Screen Shot 2020-02-19 at 10 03 15 PM" src="https://user-images.githubusercontent.com/4223814/74847727-2a051580-5365-11ea-9645-aaa38e102158.png">
Thanks

**Comment by bangtiray** [comment]
Make full access for all user first

**Comment by Mahwou** [comment]
Run this command
"composer require laravel/helpers"

**Comment by alanwhitmore** [comment]
We have fixed issues in the new release. please check and let me know if you still find it.
