### ISSUE TITLE
Getting Error When Create New Module

### ISSUE THREAD

**Issue by shaileshsiddhiinfosoft** [FTXInfotech/laravel-adminpanel#605]
Getting Error When Create New Module
Please Help

Call to undefined function Bvipul\Generator\Repositories\title_case()

http://prntscr.com/r9f56h

**Comment by anupalhub** [comment]
Are you able to fix it?

**Comment by ibaishya807** [comment]
run composer update

**Comment by alanwhitmore** [comment]
We have fixed issues in the new release. please check and let me know if you still find it.

**Comment by friendfill4** [comment]
Still i am facing same issue after composer update
