### ISSUE TITLE
The Mix manifest does not exist. (View: C:\xampp\htdocs\3-laravel-adminpanel-master\resources\views\frontend\layouts\app.blade.php)

### ISSUE THREAD

**Issue by packerdency** [FTXInfotech/laravel-adminpanel#634]
This is the error am getting
The Mix manifest does not exist. (View: C:\xampp\htdocs\3-laravel-adminpanel-master\resources\views\frontend\layouts\app.blade.php)

**Comment by sumantablog** [comment]
Hi @packerdency 

Follow the below step for resolve the `issue`
`- [ ] npm instal`

- [ ] npm run dev

now run the project

**Comment by alanwhitmore** [comment]
We have fixed issues in the new release. please check and let me know if you still find it.
