### ISSUE TITLE
getting error during installation

### ISSUE THREAD

**Issue by flik** [FTXInfotech/laravel-adminpanel#651]
Hi,

need some help.

here is detail:

`Successfully created laravel_adminpanel database

   Doctrine\DBAL\Schema\SchemaException  : There is no column with name 'created_by' on table 'users'.

  at C:\xampp\htdocs\laravel-adminpanel\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\SchemaException.php:82
    78|      * @return \Doctrine\DBAL\Schema\SchemaException
    79|      */
    80|     public static function columnDoesNotExist($columnName, $table)
    81|     {
  > 82|         return new self(
    83|             sprintf("There is no column with name '%s' on table '%s'.", $columnName, $table),
    84|             self::COLUMN_DOESNT_EXIST
    85|         );
    86|     }

  Exception trace:

  1   Doctrine\DBAL\Schema\SchemaException::columnDoesNotExist("created_by", "users")
      C:\xampp\htdocs\laravel-adminpanel\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\Table.php:658

  2   Doctrine\DBAL\Schema\Table::getColumn("created_by")
      C:\xampp\htdocs\laravel-adminpanel\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\Table.php:323
`

**Comment by alanwhitmore** [comment]
We have fixed issues in the new release. please check and let me know if you still find it.
