### ISSUE TITLE
Error during new user registration

### ISSUE THREAD

**Issue by hendisantika** [FTXInfotech/laravel-adminpanel#668]
Error during new user registration.

![image](https://user-images.githubusercontent.com/3713580/90612473-47db0680-e232-11ea-808c-bb8634d9730f.png)

Any advice?
Thank You

**Comment by krguptaa** [comment]
Hello @hendisantika ,

Can you please check your server is running or not?

**Comment by haseebJaved21** [comment]
@hendisantika  please put your mail credentials in .env file

**Comment by hendisantika** [comment]
HI @krguptaa & @haseebJaved21 , I already set smtp email using mailtrap.io then put in my .env file. My server is ok. That's why I can run the project then try register new user it turn error.

**Comment by alanwhitmore** [comment]
you need to add new SMTP details in .env.

**Comment by hendisantika** [comment]
I didn't see this issue was solve @alanwhitmore
