### ISSUE TITLE
Module Generator

### ISSUE THREAD

**Issue by Mahwou** [FTXInfotech/laravel-adminpanel#713]
I can't find the module generator, and I wish to create a module how can I go about it?

**Comment by NModern** [comment]
Yeah. I loved this admin-panel because of generator

**Comment by Mahwou** [comment]
Have you tried to find out about how we can see the generator from the current version because i can't find it whereas in the previous version we can find it there

**Comment by NModern** [comment]
I think we need to wait or write it by ourselves.

**Comment by alanwhitmore** [comment]
we have removed the module generator in the new version. we will add this very soon after rewriting it
