### ISSUE TITLE
installing problem run command composer install error

### ISSUE THREAD

**Issue by abhikashbabu** [FTXInfotech/laravel-adminpanel#770]
C:\Users\RED_X\Documents\Downloads\Compressed\laravel-adminpanel-master\laravel-adminpanel-master>composer install
A script named cc would override a Composer command and has been skipped
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^7.2 but your php version (8.1.1) does not satisfy that requirement.
  Problem 2
    - albertcht/invisible-recaptcha is locked to version v1.9.4 and an update of this package was not requested.
    - albertcht/invisible-recaptcha v1.9.4 requires php ^5.6.4 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 3
    - altek/accountant is locked to version v1.3.1 and an update of this package was not requested.
    - altek/accountant v1.3.1 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 4
    - altek/eventually is locked to version v1.0.9 and an update of this package was not requested.
    - altek/eventually v1.0.9 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 5
    - divineomega/laravel-password-exposed-validation-rule is locked to version v2.2.0 and an update of this package was not requested.
    - divineomega/laravel-password-exposed-validation-rule v2.2.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 6
    - divineomega/password_exposed is locked to version v3.1.1 and an update of this package was not requested.
    - divineomega/password_exposed v3.1.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 7
    - divineomega/psr-18-guzzle-adapter is locked to version v1.0.0 and an update of this package was not requested.
    - divineomega/psr-18-guzzle-adapter v1.0.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 8
    - dragonmantank/cron-expression is locked to version v2.3.0 and an update of this package was not requested.
    - dragonmantank/cron-expression v2.3.0 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 9
    - facade/flare-client-php is locked to version 1.3.2 and an update of this package was not requested.
    - facade/flare-client-php 1.3.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 10
    - facade/ignition is locked to version 1.16.1 and an update of this package was not requested.
    - facade/ignition 1.16.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 11
    - facade/ignition-contracts is locked to version 1.0.0 and an update of this package was not requested.
    - facade/ignition-contracts 1.0.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 12
    - filp/whoops is locked to version 2.7.3 and an update of this package was not requested.
    - filp/whoops 2.7.3 requires php ^5.5.9 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 13
    - fzaninotto/faker is locked to version v1.9.1 and an update of this package was not requested.
    - fzaninotto/faker v1.9.1 requires php ^5.3.3 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 14
    - laminas/laminas-diactoros is locked to version 2.3.0 and an update of this package was not requested.
    - laminas/laminas-diactoros 2.3.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 15
    - laminas/laminas-zendframework-bridge is locked to version 1.0.4 and an update of this package was not requested.
    - laminas/laminas-zendframework-bridge 1.0.4 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 16
    - laravel/framework is locked to version v6.18.20 and an update of this package was not requested.
    - laravel/framework v6.18.20 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 17
    - laravel/passport is locked to version v9.2.1 and an update of this package was not requested.
    - laravel/passport v9.2.1 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 18
    - laravel/socialite is locked to version v4.4.1 and an update of this package was not requested.
    - laravel/socialite v4.4.1 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 19
    - lcobucci/jwt is locked to version 3.3.2 and an update of this package was not requested.
    - lcobucci/jwt 3.3.2 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 20
    - mnapoli/front-yaml is locked to version 1.7.0 and an update of this package was not requested.
    - mnapoli/front-yaml 1.7.0 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 21
    - nunomaduro/collision is locked to version v3.0.1 and an update of this package was not requested.
    - nunomaduro/collision v3.0.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 22
    - nyholm/psr7 is locked to version 1.3.0 and an update of this package was not requested.
    - nyholm/psr7 1.3.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 23
    - opis/closure is locked to version 3.5.5 and an update of this package was not requested.
    - opis/closure 3.5.5 requires php ^5.4 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 24
    - paragonie/random_compat is locked to version v9.99.99 and an update of this package was not requested.
    - paragonie/random_compat v9.99.99 requires php ^7 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 25
    - php-http/discovery is locked to version 1.8.0 and an update of this package was not requested.
    - php-http/discovery 1.8.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 26
    - psr/http-client is locked to version 1.0.0 and an update of this package was not requested.
    - psr/http-client 1.0.0 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 27
    - spatie/laravel-html is locked to version 2.26.0 and an update of this package was not requested.
    - spatie/laravel-html 2.26.0 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 28
    - spatie/laravel-permission is locked to version 3.13.0 and an update of this package was not requested.
    - spatie/laravel-permission 3.13.0 requires php ^7.2.5 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 29
    - symfony/event-dispatcher-contracts is locked to version v1.1.7 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v1.1.7 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 30
    - symfony/finder is locked to version v4.4.10 and an update of this package was not requested.
    - symfony/finder v4.4.10 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 31
    - symfony/process is locked to version v4.4.10 and an update of this package was not requested.
    - symfony/process v4.4.10 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 32
    - symfony/psr-http-message-bridge is locked to version v2.0.0 and an update of this package was not requested.
    - symfony/psr-http-message-bridge v2.0.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 33
    - symfony/routing is locked to version v4.4.10 and an update of this package was not requested.
    - symfony/routing v4.4.10 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 34
    - tijsverkoyen/css-to-inline-styles is locked to version 2.2.2 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles 2.2.2 requires php ^5.5 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 35
    - torann/geoip is locked to version 1.2.1 and an update of this package was not requested.
    - torann/geoip 1.2.1 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 36
    - yajra/laravel-datatables-oracle is locked to version v9.10.2 and an update of this package was not requested.
    - yajra/laravel-datatables-oracle v9.10.2 requires php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 37
    - beyondcode/laravel-self-diagnosis is locked to version 1.4.3 and an update of this package was not requested.
    - beyondcode/laravel-self-diagnosis 1.4.3 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 38
    - codedungeon/phpunit-result-printer is locked to version 0.26.2 and an update of this package was not requested.
    - codedungeon/phpunit-result-printer 0.26.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 39
    - composer/composer is locked to version 1.10.7 and an update of this package was not requested.
    - composer/composer 1.10.7 requires php ^5.3.2 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 40
    - composer/semver is locked to version 1.5.1 and an update of this package was not requested.
    - composer/semver 1.5.1 requires php ^5.3.2 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 41
    - doctrine/dbal is locked to version 2.10.2 and an update of this package was not requested.
    - doctrine/dbal 2.10.2 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 42
    - doctrine/event-manager is locked to version 1.1.0 and an update of this package was not requested.
    - doctrine/event-manager 1.1.0 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 43
    - facade/ignition-code-editor is locked to version 1.0.1 and an update of this package was not requested.
    - facade/ignition-code-editor 1.0.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 44
    - facade/ignition-tinker-tab is locked to version 1.0.1 and an update of this package was not requested.
    - facade/ignition-tinker-tab 1.0.1 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 45
    - friendsofphp/php-cs-fixer is locked to version v2.16.3 and an update of this package was not requested.
    - friendsofphp/php-cs-fixer v2.16.3 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 46
    - hamcrest/hamcrest-php is locked to version v2.0.0 and an update of this package was not requested.
    - hamcrest/hamcrest-php v2.0.0 requires php ^5.3|^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 47
    - maximebf/debugbar is locked to version v1.16.3 and an update of this package was not requested.
    - maximebf/debugbar v1.16.3 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 48
    - mockery/mockery is locked to version 1.4.0 and an update of this package was not requested.
    - mockery/mockery 1.4.0 requires php ^7.3.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 49
    - myclabs/deep-copy is locked to version 1.9.5 and an update of this package was not requested.
    - myclabs/deep-copy 1.9.5 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 50
    - phar-io/manifest is locked to version 1.0.3 and an update of this package was not requested.
    - phar-io/manifest 1.0.3 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 51
    - phar-io/version is locked to version 2.0.1 and an update of this package was not requested.
    - phar-io/version 2.0.1 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 52
    - php-cs-fixer/diff is locked to version v1.3.0 and an update of this package was not requested.
    - php-cs-fixer/diff v1.3.0 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 53
    - phpdocumentor/reflection-docblock is locked to version 5.1.0 and an update of this package was not requested.
    - phpdocumentor/reflection-docblock 5.1.0 requires ext-filter ^7.1 -> it has the wrong version installed (8.1.1).
  Problem 54
    - phpdocumentor/type-resolver is locked to version 1.2.0 and an update of this package was not requested.
    - phpdocumentor/type-resolver 1.2.0 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 55
    - phpro/grumphp is locked to version v1.0.0 and an update of this package was not requested.
    - phpro/grumphp v1.0.0 requires php ^7.3 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 56
    - phpspec/prophecy is locked to version v1.10.3 and an update of this package was not requested.
    - phpspec/prophecy v1.10.3 requires php ^5.3|^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 57
    - phpunit/php-code-coverage is locked to version 7.0.10 and an update of this package was not requested.
    - phpunit/php-code-coverage 7.0.10 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 58
    - phpunit/php-file-iterator is locked to version 2.0.2 and an update of this package was not requested.
    - phpunit/php-file-iterator 2.0.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 59
    - phpunit/php-timer is locked to version 2.1.2 and an update of this package was not requested.
    - phpunit/php-timer 2.1.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 60
    - phpunit/php-token-stream is locked to version 3.1.1 and an update of this package was not requested.
    - phpunit/php-token-stream 3.1.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 61
    - phpunit/phpunit is locked to version 8.5.8 and an update of this package was not requested.
    - phpunit/phpunit 8.5.8 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 62
    - sebastian/code-unit-reverse-lookup is locked to version 1.0.1 and an update of this package was not requested.
    - sebastian/code-unit-reverse-lookup 1.0.1 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 63
    - sebastian/comparator is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/comparator 3.0.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 64
    - sebastian/diff is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/diff 3.0.2 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 65
    - sebastian/environment is locked to version 4.2.3 and an update of this package was not requested.
    - sebastian/environment 4.2.3 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 66
    - sebastian/exporter is locked to version 3.1.2 and an update of this package was not requested.
    - sebastian/exporter 3.1.2 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 67
    - sebastian/global-state is locked to version 3.0.0 and an update of this package was not requested.
    - sebastian/global-state 3.0.0 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 68
    - sebastian/object-enumerator is locked to version 3.0.3 and an update of this package was not requested.
    - sebastian/object-enumerator 3.0.3 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 69
    - sebastian/object-reflector is locked to version 1.1.1 and an update of this package was not requested.
    - sebastian/object-reflector 1.1.1 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 70
    - sebastian/recursion-context is locked to version 3.0.0 and an update of this package was not requested.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 71
    - sebastian/resource-operations is locked to version 2.0.1 and an update of this package was not requested.
    - sebastian/resource-operations 2.0.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 72
    - sebastian/type is locked to version 1.1.3 and an update of this package was not requested.
    - sebastian/type 1.1.3 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 73
    - spatie/laravel-web-tinker is locked to version 1.7.3 and an update of this package was not requested.
    - spatie/laravel-web-tinker 1.7.3 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 74
    - theseer/tokenizer is locked to version 1.1.3 and an update of this package was not requested.
    - theseer/tokenizer 1.1.3 requires php ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 75
    - webmozart/assert is locked to version 1.9.0 and an update of this package was not requested.
    - webmozart/assert 1.9.0 requires php ^5.3.3 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 76
    - laravel/framework v6.18.20 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - laravel/tinker v1.0.10 requires illuminate/console ~5.1|^6.0 -> satisfiable by laravel/framework[v6.18.20].
    - laravel/tinker is locked to version v1.0.10 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xempp 8.0\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-filter` to temporarily ignore these required extensions

**Comment by abhikashbabu** [comment]
i  update composer but error found C:\Users\RED_X\Documents\Downloads\Compressed\laravel-adminpanel-master\laravel-adminpanel-master>composer update
A script named cc would override a Composer command and has been skipped
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.3 but your php version (8.1.1) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires facade/ignition-code-editor ^1.0 -> satisfiable by facade/ignition-code-editor[1.0.0, 1.0.1, 1.0.x-dev].
    - facade/ignition-code-editor[1.0.0, ..., 1.0.x-dev] require php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 3
    - altek/accountant[v1.2.0, ..., v1.x-dev] require php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
    - Root composer.json requires altek/accountant ^1.2 -> satisfiable by altek/accountant[v1.2.0, ..., v1.x-dev].

**Comment by AKS144** [comment]
php u have installed  i.e. 8.1.1
composer.json change  php "7.2|8.1.1" 
then try  composer install --ignore-platform-reqs
